language: node_js
node_js: 
  - "stable"
services:
  - postgresql
before_script:
  - psql -c 'create database teamwork-test;' -U postgres
cache: npm
script: 
  - npm run test
notifications: 
  email: false
after_success:
  - npm run coveralls